[package]
name = "dagnn_rs"
version = "0.0.0"
description = "DAG Neural Net in Rust"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[dependencies]
num-traits = "0.2.17"
rand = "0.8.5"
